name: build 2r2t

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # every day at midnight
  push:
    branches:
      - main
    paths:
      - 2r2t/**

permissions:
  actions: read
  packages: write

concurrency:
  group: 2r2t-azul-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  build_and_push:
    name: "2r2t_${{ matrix.tag }}_azul"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - 17
    steps:
      - name: Git checkout for Github repository workspace
        uses: actions/checkout@v3

      - name: Setup QEMU for multiarch builds
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: "v0.8.2"
          buildkitd-flags: --debug

      - name: Login to registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: ./2r2t
          file: ./2r2t/${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/omega-network/yolks:2r2t_${{ matrix.tag }}_azul